<!doctype html>
<html lang="de-DE">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/style/style.css">
    <link rel="icon" type="image/x-icon" href="/style/home_organicer.png">
    <title>Home‑Organizer</title>
</head>
<body class="dashboard-body">
<header class="topbar">
    <div class="container">
        <div class="brand">Home‑Organizer</div>
        <form action="/logout-submit" method="post" class="logout topbar-actions">
            <input type="hidden" name="destroySession" value="1">
            <input type="submit" value="Logout" class="btn btn-outline">
        </form>
    </div>
</header>
