<?php

require_once(__DIR__ . '/header.phtml');
?>

    <div class="page-warehous-wrapper">
        <div class="Lager">
            <h1>Lager</h1>
            <form action="/warehouse-submit" method="post" class="item-form">

                <div class="form-group">
                    <label for="name">Titel</label>
                    <input type="text" id="name" name="name" maxlength="30" required>
                </div>

                <div class="form-group">
                    <label for="category">Kategorie</label>
                    <input type="text" id="category" name="category" maxlength="30" required>
                </div>

                <div class="form-group">
                    <label for="amount">Anzahl</label>
                    <input type="number" id="amount" name="amount" min="1" required>
                </div>

                <button type="submit" class="btn">Speichern</button>

            </form>
        </div>
    </div>

<?php
require_once(__DIR__ . '/footer.phtml');
?>